import ae2009Data from './data/ae-2009.sectors.json'
import at1969Data from './data/at-1969.sectors.json'
import au1953Data from './data/au-1953.sectors.json'
import az2016Data from './data/az-2016.sectors.json'
import be1925Data from './data/be-1925.sectors.json'
import bh2002Data from './data/bh-2002.sectors.json'
import br1940Data from './data/br-1940.sectors.json'
import ca1978Data from './data/ca-1978.sectors.json'
import cn2004Data from './data/cn-2004.sectors.json'
import de1927Data from './data/de-1927.sectors.json'
import de1932Data from './data/de-1932.sectors.json'
import es1991Data from './data/es-1991.sectors.json'
import fr1969Data from './data/fr-1969.sectors.json'
import gb1948Data from './data/gb-1948.sectors.json'
import hu1986Data from './data/hu-1986.sectors.json'
import it1914Data from './data/it-1914.sectors.json'
import it1922Data from './data/it-1922.sectors.json'
import it1953Data from './data/it-1953.sectors.json'
import jp1962Data from './data/jp-1962.sectors.json'
import mc1929Data from './data/mc-1929.sectors.json'
import mx1962Data from './data/mx-1962.sectors.json'
import nl1948Data from './data/nl-1948.sectors.json'
import pt2008Data from './data/pt-2008.sectors.json'
import qa2004Data from './data/qa-2004.sectors.json'
import ru2014Data from './data/ru-2014.sectors.json'
import sa2021Data from './data/sa-2021.sectors.json'
import sg2008Data from './data/sg-2008.sectors.json'
import tr2005Data from './data/tr-2005.sectors.json'
import us2012Data from './data/us-2012.sectors.json'
import us2022Data from './data/us-2022.sectors.json'
import us2023Data from './data/us-2023.sectors.json'

// Auto-generated by generate_track_registry.py -- do not hand-edit.
// Re-run that script after adding a new *.sectors.json to src/data/.
export const TRACKS = [
  { id: 'ae-2009', data: ae2009Data },
  { id: 'at-1969', data: at1969Data },
  { id: 'au-1953', data: au1953Data },
  { id: 'az-2016', data: az2016Data },
  { id: 'be-1925', data: be1925Data },
  { id: 'bh-2002', data: bh2002Data },
  { id: 'br-1940', data: br1940Data },
  { id: 'ca-1978', data: ca1978Data },
  { id: 'cn-2004', data: cn2004Data },
  { id: 'de-1927', data: de1927Data },
  { id: 'de-1932', data: de1932Data },
  { id: 'es-1991', data: es1991Data },
  { id: 'fr-1969', data: fr1969Data },
  { id: 'gb-1948', data: gb1948Data },
  { id: 'hu-1986', data: hu1986Data },
  { id: 'it-1914', data: it1914Data },
  { id: 'it-1922', data: it1922Data },
  { id: 'it-1953', data: it1953Data },
  { id: 'jp-1962', data: jp1962Data },
  { id: 'mc-1929', data: mc1929Data },
  { id: 'mx-1962', data: mx1962Data },
  { id: 'nl-1948', data: nl1948Data },
  { id: 'pt-2008', data: pt2008Data },
  { id: 'qa-2004', data: qa2004Data },
  { id: 'ru-2014', data: ru2014Data },
  { id: 'sa-2021', data: sa2021Data },
  { id: 'sg-2008', data: sg2008Data },
  { id: 'tr-2005', data: tr2005Data },
  { id: 'us-2012', data: us2012Data },
  { id: 'us-2022', data: us2022Data },
  { id: 'us-2023', data: us2023Data },
]
