"""
Scans src/data/*.sectors.json and generates src/trackRegistry.js --
the import list + TRACKS array that App.jsx consumes. Re-run this any
time a new circuit's *.sectors.json is added; it fully regenerates the
file, so it's always in sync with what's actually in src/data/.
"""
import json
import os
import re

DATA_DIR = "src/data"
OUT_PATH = "src/trackRegistry.js"


def to_camel_case(circuit_id):
    parts = re.split(r"[-_]", circuit_id)
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


files = sorted(f for f in os.listdir(DATA_DIR) if f.endswith(".sectors.json"))

imports = []
entries = []
for fname in files:
    circuit_id = fname.replace(".sectors.json", "")
    var_name = to_camel_case(circuit_id) + "Data"
    imports.append(f"import {var_name} from './data/{fname}'")
    entries.append(f"  {{ id: '{circuit_id}', data: {var_name} }},")

content = "\n".join(imports) + "\n\n"
content += "// Auto-generated by generate_track_registry.py -- do not hand-edit.\n"
content += "// Re-run that script after adding a new *.sectors.json to src/data/.\n"
content += "export const TRACKS = [\n"
content += "\n".join(entries) + "\n"
content += "]\n"

with open(OUT_PATH, "w") as f:
    f.write(content)

print(f"Wrote {OUT_PATH} with {len(files)} tracks:")
for fname in files:
    print(f"  {fname}")
